### PR TITLE
Add ability to manually assign the state value_type for a child node

### PR DESCRIPTION
**Pull request by PhracturedBlue**
## Description:
**Note: it would be helpful if you resync this branch to 'dev', otherwise the diff is unmanageable**

Hopefully this is more to your liking.  Adds the ability to assign which value_type is assigned to the 'state' attribute for each entity (using the new one-child-one-entity branch)

This provides a method to choose which state in the S_POWER presentation becomes the primary state.  the others are just attributes.

Also,
Do you have a list of things that need to be implemented before this can be merged upstream?  Now that I've spent some time with it, I like the one-child-one-entity approach, and would like to help get it ready to merge.

## Example entry for `configuration.yaml` (if applicable):
```yaml
mysensors:
  gateways:
    - device: mqtt
      topic_in_prefix: 'mytest-out'
      topic_out_prefix: 'mytest-in'
      nodes:
        5:
          children:
            1:
              state_value_type: 'V_WATT'
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

```

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Hi!

I've squashed and rebased my branch. Please rebase your branch so that you only add one commit on top of my first (squashed) commit. Then I'll have a closer look.

Generally I don't like adding config options, but I guess it could be a compromise. Originally I had thought that only the first reported value would be used as state for children and entities that report more than one value and doesn't use more than one for the entity state. Some entities use more than one value for state, eg cover, climate, light.

**Comment by PhracturedBlue** [comment]
I don't think there is any way to do this without a config option.  My sensors do present in order, but there is no guarantee that when restarting home-assistant it doesn't start listening between updates (which is exactly what I've seen with the current trunk code).

FYI I have another patch that builds on top of this patch that allows defining a custom schema (for instance I have sensors that use S_CUSTOM that I want to assign a state for).  That one isn't quite ready yet, but it also requires new configuration options.

That new code has configuration like:
```yaml
mysensors:
  gateways:
    - device: mqtt
      topic_in_prefix: 'mytest-out'
      topic_out_prefix: 'mytest-in'
      nodes:
        5:
          children:
            3:
              schema:
                platform: 'sensor'
                type: 'V_FLOW'
```
That upcoming patch could also provide the capabilities of this patch.  I was planning on submitting these as two separate features, but if you prefer, I can merge in only the 'schema' patch, which would reduce the number of configuration options.

**Comment by PhracturedBlue** [comment]
Also , I've rebased my patch

**Comment by MartinHjelmare** [comment]
This, original, branch will only add one entity per child and platform so the problem of conflicting entity_ids will be gone. The user if reporting more than one value, would probably randomly see one of the values as state for the entity of the child. This would be avoided via documentation and notification.

But I think a config addition could be ok.

I'm not sure why you want to add a custom schema för S_CUSTOM. Instead we could allow all V_TYPES for S_CUSTOM? We should decide the best api but still flexible api and stick to that. No need to make that configurable.

**Comment by PhracturedBlue** [comment]
I think we have a different idea of how mysensors should be supported.  My understanding of the mysensors serial API is that the presentation<->type mapping is a recommendation and not a hard requirement.  I don't see why home-assistant should enforce a specific schema.  In my opinion it should automatically work if the recommendations are followed, and allow a user to specify the configuration if they are not.  I do not think home-assistant should be able to dictate how my nodes are configured.

That said, the primary I need addressed though is the one currently solved by the current patch.  Allowing any V_VALUE for S_CUSTOM would probably be fine for my other sensors in addition to this patch.  So I don't think I absolutely need to be able to design a custom presentation->type mapping for my own needs even if I do think it is a good feature.

**Comment by MartinHjelmare** [comment]
Hi!

I'm working on implementing unique ids for mysensors entities. That will render the one child one entity change moot and this PR will also not be needed.

The user will be able to have multiple value types per child and the entity_id will not randomly change between restarts. The user will also be able to customize the entity_id.

Regarding allowing any value type for S_CUSTOM that's a change planned in the pymysensors library. PR for that is welcome.

**Pull request closed without merging**
